# Generated by Django 4.0.1 on 2022-02-17 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='reference_url',
            field=models.URLField(null=True),
        ),
    ]
