# Generated by Django 4.0.1 on 2022-02-18 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_answer_reference_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='reference_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
